language: java

scala:
- 2.11.12

jdk:
- openjdk8

services:
- postgresql

addons:
 - postgresql: '9.6'

env:
  global:
  - secure: ji7CJ/J6ljZQ8rm0HsBMA8UuRT943xFEMApoxH7y6kF6aBswROAA1kYf+OL7pvMH8Dr1RlCBE7RZFQDwWC+7i9LN8VOeuSx5k/5e8afKxI03qctx9nFm2lM0hnAzyhCF8cPhG+b3r+dq98jSgpyCA1vYIhXNqK/vpPIv60VSSEWRTcBhNEdhC8UlEH6B7qqGqO4B311Xr/Qlphxblvf4xiSI9vKYNFGBUqgyxtbIYDRSS3F+KN0r/qBKm2aY84am/o7VYbE6g0OPFU3/SfhIBzZp2RgXdAVCaSRRw8dfco6CCugCgo4O8Vm400khDFOGi2ukkhgkmjH0Li/sPOIzFugj8tNtsT2bolt4hSxJ8FzXepsyq2KWKDnCaf/xX9BaQZJJSlhh3vbAL/3MtiZvQ5m+zQ6RDv8LfRd/ubGYtNP5RWxqlY6/6H3I5Oz7Q7TVb5Wp7rNmr48cdvjJWQ2prdNesAiIqrRw6OxiTxfU+EXn8lVUdv5kJmI4gUGHGcw2CpXQykhIQSPo3Y0BwJCTmU7V6Po+h/WOrn3e4rQe1Iwq28LSM9afSGL9QDqDpAYMi5znE+xqFsGwbUEDiS5uMJnKO3YTq3fyYCzJLbWxQYG0yMWUyW3ACSfyYeAkcxFv2O+j2AJgQVi8osrPK5yzr5AgODn0gBIi3+mSwpKpoHU=
  - secure: eiQO0U1IG2HxSZnyrbJQ/+e1tcCBisOr7JUN90dHYTSE6619xV49hUkwXXEPVXG2NNEbBvqmRJd5CeYvJH6t2Ku2Za3WpaBpA+Ln9OxjfRZei+k5EUdbbgjwjnDVjHi2C+WZolNwNOXSMKGTirhWi6u0kugbY50ENByS6jBle9SQsdxx73rqtKJNCpAm65DSR0KzxadP1NoATpe21KDFjxlgTaLrSdWR6ZwD6EShOzD6XyT73znZqm8NqWfT8k0pNfaNuAxhb+EJciEaWDzXrMDs4XySY/ebMJKTXjtHvQDnQ5aLWEG0plb3aRlfidXnU2cHztpUdSK+NUZOwz0Ze8VGldPRZm2QS1HRxHoCPSdrbLmU+8UpLIsC965TqYxnR20bCs5g4RSXZ1eaxK/E3f3WsTQHgmHfKPAFs5gpbdiIV65KdRgqQkL3iF9BDx1e9prU0BWbU8k4t371KY1ZX88jfddD09LWa8AEg9bzoWHGAKeJUozqwh4n6ePXvMDjIqOelLclPW6NfE0XbLEJhZSZKc6y8JbgwQwAnjyloQO7fakHNHp68XL03k3vVGwh5U8izNFJbIXTGXYfiTc54CnTN5buoQPfqwEHTiNK2IK9dnhQADXTsDe7wNE2LgWBZ1F5vHbx39899Wgk30WKck/MEjEWxgPD+NSR6kyBBHQ=

before_script:
- echo "TRAVIS_SECURE_ENV_VARS=$TRAVIS_SECURE_ENV_BARS"
- echo "TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR"
- echo "SVN_USERNAME=$SVN_USERNAME"
- if [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    svn --username $SVN_USERNAME --password $SVN_PASSWORD --non-interactive co http://source.gemini.edu/software/lch-credentials $TRAVIS_BUILD_DIR/lch-credentials;
    ls $TRAVIS_BUILD_DIR;
    bash $TRAVIS_BUILD_DIR/lch-credentials/trunk/link.sh -v $TRAVIS_BUILD_DIR;
    fi
  - if [ $TRAVIS_SECURE_ENV_VARS == false ]; then
    cp $TRAVIS_BUILD_DIR/project/OcsCredentials.scala.template $TRAVIS_BUILD_DIR/project/OcsCredentials.scala;
    fi

- psql -Upostgres
- psql -c 'create database travis_ci_test;' -U postgres
- psql -c 'create user lch;' -U postgres
- psql -c 'create database lch_test;' -U postgres
- psql -c 'grant all privileges on database lch_test to lch;' -U postgres
- psql -c 'create database lch_dev;' -U postgres
- psql -c 'grant all privileges on database lch_dev to lch;' -U postgres

script:
- echo "TRAVIS_SECURE_ENV_VARS=$TRAVIS_SECURE_ENV_BARS"
- echo "TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR"
- echo "SVN_USERNAME=$SVN_USERNAME: 
- echo "Running TRAVIS script."
- if [[ -f "$TRAVIS_BUILD_DIR/edu.gemini.lch.services/src/main/scala/edu/gemini/lch/services/impl/JSpOCCredentials.scala"
  ]]; then echo "Credentials exist"; else echo "Credentials do not exist"; fi
- mvn -U -B clean install
